#!/bin/bash

echo "Enter file name: "
read asm_file

rm ${asm_file%.asm}.o
echo "Deleted ${asm_file%.asm}.o" 

rm ${asm_file%.asm}
echo "Deleted ${asm_file%.asm} executable file\n"
echo "Attempting nasm compilation ...\n"

nasm -f elf $asm_file -o ${asm_file%.asm}.o
echo "Assembling complete, linking file...\n"
  ${asm_file%.asm}.o -s -o ${asm_file%.asm}
echo "Link complete, ready to execute...\n"


