#!/bin/bash

read -p "Enter file name: " asm_file

if [ -e "$asm_file.asm" ]; then
  echo "File '$asm_file.asm' found in directory"

  if [ -e "$asm_file.o" ]; then
    echo "Found executable file, attempting deleting"
    echo "Attempting command rm '$asm_file.o'"
    rm "$asm_file.o"

    if [ $? -eq 0 ];then
		echo "Successfully deleted file"
		echo "Attempting NASM compilation"
	else
		echo "Unable to delete fie"
		exit(1)
	fi
	
    nasm -f elf "$asm_file.asm"

	if [ $? -eq 0 ];then
		echo "Assembling complete, linking file"
	else
		echo "Unable to compile file"
		exit(1)
	fi

    ld -m elf_i386 -s -o "$asm_file" "$asm_file.o"
	if [ $? -eq 0 ]; then
		echo "Success on linking"
	else
		echo "Error linking file"
		exit(1)
	fi
  else
    nasm -f elf "$asm_file.asm"
    echo "Assembling complete, linking file"
    ld -m elf_i386 -s -o "$asm_file" "$asm_file.o"
  fi
else
  echo "File not found"
  exit 1
fi
